[workspace]

members = [
    "inject_metering",
    "cmd",
]

[profile.dev]
opt-level = 0
overflow-checks = false
debug = 0
strip = "debuginfo"

[profile.release]
lto=true
opt-level = 3
overflow-checks = false
debug = 0
strip = "symbols"
debug-assertions = false