[package]
name = "scs_sdk"
version = "0.0.1"
authors = ["Geoff Ramseyer"]
license = "MIT OR Apache-2.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
static_assertions = "0.1"
scs_callable_attr = {path = "../scs_callable_attr"}


