[package]
name = "scs_callable_attr"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = {version = "1.0",  features = ["full"] }
quote = "1.0"
sha2 = "0.10"
hex = "0.4"
