(module
  (memory 1 1)

  (func (export "size") (result i32) (memory.size))
  (func (export "load") (param i32) (result i32)
    (i32.load (local.get 0))
  )  
  (func (export "load16") (param i32) (result i32)
    (i32.load16_u (local.get 0))
  )  
  (func (export "load8") (param i32) (result i32)
    (i32.load8_u (local.get 0))
  )
  (func (export "store") (param i32 i32)
    (i32.store (local.get 0) (local.get 1))
  )
  (func (export "store8") (param i32 i32)
    (i32.store8 (local.get 0) (local.get 1))
  )
  (func (export "store16") (param i32 i32)
    (i32.store16 (local.get 0) (local.get 1))
  )
)
