#pragma once

#include "storage_proxy/proxy_applicator.h"

#include "xdr/storage_delta.h"

namespace scs
{

// writes generated by one tx on one key
struct StorageProxyValue
{
	ProxyApplicator applicator;

	StorageProxyValue(std::optional<StorageObject> const& obj)
		: applicator(obj)
	{}
};

} /* scs */
