#pragma once

#include "storage_proxy/proxy_applicator.h"

#include "xdr/storage_delta.h"

namespace scs
{

// writes generated by one tx on one key
struct StorageProxyValue
{
	//DeltaVector vec;
	std::vector<StorageDelta> vec;

	ProxyApplicator applicator;

	StorageProxyValue(std::optional<StorageObject> const& obj)
		: vec()
		, applicator(obj)
	{}

	DeltaTypeClass const& get_tc()
	{
		return applicator.get_tc();
	}
};

} /* scs */
