[package]
name = "commitments"
version = "0.1.0"
edition = "2021"

[dependencies]
curve25519-dalek = "2"
sha3 = { version = "0.8", default-features = false }

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]